- name: ec2 launcher
  hosts: localhost
  connection: local
  tasks:
  - name: launching ec2
    ec2:
      key_name: ec2_instance
      instance_type: t2.micro
      image:  ami-0975ce566eec139c3
      region: ap-southeast-2
      wait: yes
      group: default
      count: 1
      vpc_subnet_id: subnet-9dec0bfb
      assign_public_ip: yes
